// Exit codes for selfci

pub const EXIT_NO_VCS_FOUND: i32 = 1;
pub const EXIT_INVALID_VCS_TYPE: i32 = 2;
pub const EXIT_WORKDIR_CREATE_FAILED: i32 = 3;
pub const EXIT_VCS_COMMAND_FAILED: i32 = 4;
pub const EXIT_NOT_INITIALIZED: i32 = 5;
pub const EXIT_CONFIG_READ_FAILED: i32 = 6;
pub const EXIT_CONFIG_PARSE_FAILED: i32 = 7;
pub const EXIT_CHECK_FAILED: i32 = 8;
pub const EXIT_REVISION_RESOLUTION_FAILED: i32 = 9;
pub const EXIT_REVISION_INVALID_COMMIT_ID: i32 = 10;
pub const EXIT_REVISION_INVALID_OUTPUT: i32 = 11;
pub const EXIT_JOB_NOT_FOUND: i32 = 12;
pub const EXIT_JOB_WAIT_FAILED: i32 = 13;
